CREATE TABLE [tblFillPDF] (
  [FillID] AUTOINCREMENT CONSTRAINT [PrimaryKey] PRIMARY KEY UNIQUE NOT NULL,
  [SavedFileName] VARCHAR (255),
  [Signature_Name] VARCHAR (255),
  [dtDate] DATETIME,
  [Signature_Image] LONGBINARY,
  [txtFileLocation] VARCHAR (255),
  [txtFileName] VARCHAR (255),
  [txtFileFolder] VARCHAR (255),
  [PDFFileLocation] VARCHAR (255),
  [PDFFileFolder] VARCHAR (255),
  [PDFFileName] VARCHAR (255),
  [PDFSignedFileLocation] VARCHAR (255),
  [PDFSignedFileFolder] VARCHAR (255),
  [PDFSignedFileName] VARCHAR (255),
  [txtFileLocation_Claborn] VARCHAR (255),
  [txtFileName_Claborn] VARCHAR (255),
  [txtFileFolder_Claborn] VARCHAR (255),
  [PDFFileLocation_Claborn] VARCHAR (255),
  [PDFFileFolder_Claborn] VARCHAR (255),
  [PDFFileName_Claborn] VARCHAR (255),
  [PDFSignedFileLocation_Claborn] VARCHAR (255),
  [PDFSignedFileFolder_Claborn] VARCHAR (255),
  [PDFSignedFileName_Claborn] VARCHAR (255),
  [SavedFileName_Claborn] VARCHAR (255),
  [dtDate_Claborn] DATETIME,
  [Signature_Name_Claborn] VARCHAR (255)
)
